package openpass.security.data

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import android.util.Base64
import java.nio.charset.Charset
import java.security.KeyStore
import javax.crypto.Cipher
import java.security.spec.AlgorithmParameterSpec
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

class CryptoManager {

    private val keyStore = KeyStore.getInstance(ANDROID_KEYSTORE).apply {
        load(null)
    }

    private fun getSecretKey(): SecretKey {
        // Check if the key already exists in the Keystore
        val existingKey = keyStore.getEntry(KEY_ALIAS, null) as? KeyStore.SecretKeyEntry
        return existingKey?.secretKey ?: generateSecretKey()
    }

    private fun generateSecretKey(): SecretKey {
        // If key doesn't exist, generate a new one
        val keyGenerator = KeyGenerator.getInstance(ALGORITHM, ANDROID_KEYSTORE)
        val parameterSpec = KeyGenParameterSpec.Builder(
            KEY_ALIAS,
            KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
        )
            .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
            .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
            .setKeySize(256) // AES-256
            .build()
        keyGenerator.init(parameterSpec)
        return keyGenerator.generateKey()
    }

    /**
     * Encrypts plaintext and returns a Base64 string containing the IV and ciphertext.
     */
    fun encrypt(plaintext: String): String {
        val cipher = Cipher.getInstance(TRANSFORMATION)
        cipher.init(Cipher.ENCRYPT_MODE, getSecretKey())

        // The IV is generated by the cipher. We must store it with the ciphertext.
        val iv = cipher.iv
        val ciphertext = cipher.doFinal(plaintext.toByteArray(Charset.defaultCharset()))

        // Prepend the IV to the ciphertext and encode the whole thing as Base64
        val encryptedBytes = iv + ciphertext
        return Base64.encodeToString(encryptedBytes, Base64.DEFAULT)
    }

    /**
     * Decrypts a Base64 string (containing IV + ciphertext) and returns the original plaintext.
     */
    fun decrypt(ciphertext: String): String {
        val decodedBytes = Base64.decode(ciphertext, Base64.DEFAULT)
        // The first 12 bytes are the IV for AES/GCM
        val iv = decodedBytes.copyOfRange(0, 12)
        val encryptedData = decodedBytes.copyOfRange(12, decodedBytes.size)
        val cipher = Cipher.getInstance(TRANSFORMATION)
        // Explicitly defining the types for the key and spec resolves the compiler ambiguity.
        val key: SecretKey = getSecretKey()
        val spec: AlgorithmParameterSpec = GCMParameterSpec(128, iv)
        cipher.init(Cipher.DECRYPT_MODE, key, spec)
        val decryptedBytes = cipher.doFinal(encryptedData)
        return String(decryptedBytes, Charset.defaultCharset())
    }

    companion object {
        private const val ANDROID_KEYSTORE = "AndroidKeyStore"
        private const val KEY_ALIAS = "openpass_secret_key"
        private const val ALGORITHM = KeyProperties.KEY_ALGORITHM_AES
        private const val TRANSFORMATION = "AES/GCM/NoPadding"
    }
}